### ISSUE TITLE
Add name attribute to sender and recipients.

### ISSUE THREAD

**Issue by ldlsegovia** [platanus/send_grid_mailer#1]

**Comment by agustinf** [comment]
I need this!
I found this https://github.com/sendgrid/sendgrid-ruby/blob/0033e1f5fafc02a4357360950df70df2b4d0f29e/lib/sendgrid/helpers/mail/mail.rb#L784

**Comment by agustinf** [comment]
I need this! 
I did this https://github.com/platanus/send_grid_mailer/pull/8
