### ISSUE TITLE
Add API class to handle SendGrid requests

### ISSUE THREAD

**Issue by ldlsegovia** [platanus/send_grid_mailer#5]
Move this out from deliverer class.
https://github.com/platanus/send_grid_mailer/blob/v0.1.0/lib/send_grid_mailer/deliverer.rb#L25

**Comment by blackjid** [comment]
#11??

**Comment by ldlsegovia** [comment]
@blackjid I'm going to close this doing https://github.com/platanus/send_grid_mailer/issues/9
